### ISSUE TITLE
🚀 Feature: proxy requests

### ISSUE THREAD

**Issue by Shagon94** [stonith404/pocket-id#15]
### Feature description

Allowing to proxy requests, for example for sites that don't support any form of authentication, or only support authentication based on a header.

Some examples include;

- calibre-web - allows login via specific header that denotes username
- radarr/sonarr/prowlarr - has basic auth
- plain nginx - no auth at all

This feature is similar to authelia's proxy feature, where we essentially just require the user to authenticate before allowing login - https://www.authelia.com/integration/proxies/caddy/#basic-examples

### Pitch

Allows for a much easier integration and support as most self-hosted tools have basic username+pass, or no authentication at all.

**Comment by stonith404** [comment]
Thank you for your request. In my opinion this is beyond the scope of the project, as Pocket ID is designed solely to function as an OIDC provider. However, I’ve created a [guide](https://github.com/stonith404/pocket-id/blob/main/docs/proxy-services.md) on how to proxy your services through Pocket ID using [OAuth2 Proxy](https://oauth2-proxy.github.io/). Let me know if something is unclear in the guide :)

**Comment by tajkirkpatrick** [comment]
@stonith404 May you update the uptime-kuma guide (or assist me) with what the "callback url" in Pocket ID would be for a service that doesn't support oauth and you are using the oauth2-proxy container. I am having issues replicating the guide with a similar docker application.

**Comment by stonith404** [comment]
@tajkirkpatrick `https://<uptima-kuma-domain>/oauth2/callback` should work. I'll update the docs.
