### ISSUE TITLE
🐛 Bug Report: Cannot add passkey, blank account setup page

### ISSUE THREAD

**Issue by nanhoes** [stonith404/pocket-id#16]
### Reproduction steps

Going to https://mydomain.com/login/setup produces a blank page after clicking continue. Users and application config page are populated but my account page is blank.
![setup](https://github.com/user-attachments/assets/1d7cad56-9767-47fa-b792-04f76941d3d3)

### Expected behavior

Some type of setup page to add a passkey. I can access the login page but cannot add a passkey to login with.

### Actual Behavior

After clicking continue, here is the next page:
![account](https://github.com/user-attachments/assets/e9016e43-752c-4ea3-8ab9-3b606720c386)
Running using docker, private url is domain that points to reverse proxy that points to pocket

**Comment by stonith404** [comment]
Hey, thanks for your report. This should be fixed in `v0.3.1`.
