### ISSUE TITLE
🐛 Bug Report: Unable to create first user

### ISSUE THREAD

**Issue by wjbeckett** [stonith404/pocket-id#2]
### Reproduction steps

Create compose file, update .env with the correct url for my instance, start the container.
Access https://<my-url>/login/signup and click "Continue".

### Expected behavior

I should be able to create a user

### Actual Behavior

I get an error which reads: "Token is invalid or expired"

**Comment by stonith404** [comment]
I think you've opened the wrong URL. You should open `http://<your-domain>/login/setup`.

**Comment by wjbeckett** [comment]
Ah. Yes. That'll do it. 🤣
