### ISSUE TITLE
🚀 Feature:  Support more characters in usernames

### ISSUE THREAD

**Issue by alec-hs** [stonith404/pocket-id#20]
### Feature description

Support more characters in usernames. Ideally hyphen/ dash `-` and `@`

### Pitch

These are often used by lots of systems and can be mapped as an attribute so support for more chars would be great.

**Comment by stonith404** [comment]
Are `@` really used in usernames? Do you have an example of a service that uses an `@` in the username?

**Comment by alec-hs** [comment]
Some platforms user email as username - anyone who uses MS Entra as an ID source often has this requirement as UPN is name@domain

**Comment by stonith404** [comment]
This should be added in `v0.4.0`. Let me know if there are still too much constraints.
