### ISSUE TITLE
🚀 Feature: Output the urls for endpoints 

### ISSUE THREAD

**Issue by Node815** [stonith404/pocket-id#21]
### Feature description

On the settings/admin/oidc-clients page, Next to where the OIDC client and secret credentials are displayed, make it so the defaulted OIDC paths are displayed with the mapped domain in the .env file:   

![image](https://github.com/user-attachments/assets/c870c452-c3e8-4dc6-8f0a-364869d96a00)

### Pitch

In my use case, I had to open your Github page and scroll through to the https://github.com/stonith404/pocket-id#add-pocket-id-as-an-oidc-provider link to get a hint on these. 

Having the paths mapped to the domain name set in the .env file would be valuable at a glance when I have the app I'm configuring (In this case another .env file in VSCode),  Having these on the same screen I'm copying from would be a huge time saver.

**Comment by stonith404** [comment]
![Screenshot 2024-09-03 at 19 45 28](https://github.com/user-attachments/assets/ff9a48c5-5c1b-4529-98d0-5785803e24b3)

Should the "Authorization URL" and "OIDC Discovery URL" be visible by default or would you hide it under the more details?

**Comment by Node815** [comment]
Either way I think would work :)

**Comment by stonith404** [comment]
This should be added in `v0.4.0`.
