### ISSUE TITLE
🐛 Bug Report: "name" is not included in user info

### ISSUE THREAD

**Issue by John-K** [stonith404/pocket-id#22]
### Reproduction steps

When I try to use an application that looks for "name" instead of "given_name" and "family_name" in the profile claim, it errors out.

### Expected behavior

"name" should be constructed from "given_name" and "family_name" and included in the profile claim

### Actual Behavior

Application errors out that no username was returned. This is a slight bug on the application side, but "name" should be included in any case.

**Comment by John-K** [comment]
suggest fixing by adding `"name": user.FirstName + " " + user.LastName,` to https://github.com/stonith404/pocket-id/blob/8ad632e6c1cfa1c7f99f3a283ce56c8e30ada1e0/backend/internal/service/oidc_service.go#L299

**Comment by stonith404** [comment]
@danielgraycode You probably forgot to add those claims in Cloudflare:
![image](https://github.com/user-attachments/assets/10ce429c-40b6-452d-b6b6-d210b20ae8c2)

The following claims are supported: `"sub", "given_name", "family_name", "name", "email", "preferred_username"`
