### ISSUE TITLE
🐛 Bug Report: 400 error when trying to authorize

### ISSUE THREAD

**Issue by tiehfood** [stonith404/pocket-id#23]
### Reproduction steps

I tried to use Grafana with Pocket ID.
This is my current configuration:
<img width="445" alt="image" src="https://github.com/user-attachments/assets/43f83df7-d277-48fb-ab88-c0e389c0cd80">

I successfully get redirected to PocketID, but when I try to login I get a 400 error from the backend:
<img width="563" alt="image" src="https://github.com/user-attachments/assets/a02b989d-79bd-490d-9058-c87bafd09890">

Backend call: https://********************/api/oidc/authorize/new-client

### Expected behavior

If I klick on "Sign In" I should successfully be signed in.

### Actual Behavior

Backend sends a 400 error and I'm not logged in

**Comment by stonith404** [comment]
The callback URL is probably wrong. Can you verify that you've entered the correct callback URL in the Pocket ID settings?

**Comment by tiehfood** [comment]
Ah, you were right! I needed to configure the `root_url` setting in Grafana because Grafana is behind a reverse proxy.
Thanks! Great tool I really like it so far :)

**Comment by tiehfood** [comment]
Solved
