### ISSUE TITLE
🐛 Bug Report: Changing "Application Name" isn't reflected in saved passkey

### ISSUE THREAD

**Issue by sypion** [stonith404/pocket-id#28]
### Reproduction steps

Changing the "Application Name" in the Application Configuration tab does not apply the same change for saved passkeys. For example, in Bitwarden, I still see my saved passkey titled "Pocket ID"

### Expected behavior

For any newly saved passkeys, have the title of passkey reflect the new application name.

### Actual Behavior

![Screenshot 2024-09-18 at 10 00 43 AM](https://github.com/user-attachments/assets/fbd7fc26-2610-4479-b410-801996a1559c)

**Comment by stonith404** [comment]
Thanks for the report, I'll look into it. I think when you restart the container it should take the correct name, but I can't test it right now. Just as a workaround.

**Comment by sypion** [comment]
You're right! That solves it. When the container is restarted, any new passkeys generated will show the new application name.

**Comment by stonith404** [comment]
Fixed in `v0.5.2`.
