### ISSUE TITLE
🚀 Feature: Impersonation Mechanic

### ISSUE THREAD

**Issue by sypion** [stonith404/pocket-id#29]
### Feature description

Add an impersonation feature to mimic the user temporarily.

### Pitch

Impersonation through SSO platforms is really helpful when troubleshooting end-user issues. I currently use Authentik to do this, but if this was added for Pocket ID, that would be the last thing my team and I would need to transition to Pocket ID and passkeys.

**Comment by stonith404** [comment]
![Screenshot 2024-09-19 at 08 38 07](https://github.com/user-attachments/assets/6fbaa36f-3c5b-4493-8ca4-c8974a21a5cd)

There is already a "One-Time token" feature which allows you to sign in to any account as an administrator. Did you see this feature already? If so, could you please explain why it doesn’t meet your needs?

**Comment by sypion** [comment]
You are so right! I didn't catch this earlier. I will try this out and report back if I encounter any hurdles. I appreciate your support and thank you again.
