### ISSUE TITLE
🐛 Bug Report: Invalid One Time Link for New User

### ISSUE THREAD

**Issue by lcurole** [stonith404/pocket-id#3]
### Reproduction steps

Try to create a One Time Link for a new user

### Expected behavior

Expect to see a valid One Time Link for a new user

### Actual Behavior

I'm given "http://localhost/login/[object Object]" as the One Time Link for a new user

**Comment by lcurole** [comment]
I'm able to grab the token from the response from the server so I believe this is a frontend bug just not displaying it

**Comment by stonith404** [comment]
Thanks. This should be fixed in `v0.1.1`.
