### ISSUE TITLE
🚀 Feature: Add copy icons next to OIDC client information

### ISSUE THREAD

**Issue by edbourque0** [stonith404/pocket-id#32]
### Feature description

You should add copy icons next to the OIDC client information (client ID, client secret, authorization url, etc.) that automatically copies the information to your clipboard.

### Pitch

When someone selects the text from the client id, secret, etc. there is always a trailing space before the text which could lead to errors when copy/pasting the urls to another platform.

**Comment by stonith404** [comment]
Added in`v0.6.0`.
