### ISSUE TITLE
Logo not white in dark mode on mobile

### ISSUE THREAD

**Issue by edbourque0** [stonith404/pocket-id#33]
### Reproduction steps

Open Pocket ID on mobile while in dark mode.
The logo is black, which looks like there is nothing.

![IMG_6990](https://github.com/user-attachments/assets/9f76fb1b-2bf7-4086-96fa-faa8f64ff875)

### Expected behavior

Have the same behavior as the desktop version.
The bug was fixed in this issue on desktop : 
https://github.com/stonith404/pocket-id/commit/5749d0532fc38bf2fc66571878b7c71643895c9e

### Actual Behavior

Logo os shown in black, which makes it invisible.

**Comment by edbourque0** [comment]
The logo is also dark on the homepage
![image](https://github.com/user-attachments/assets/60eb3bdf-33a8-420c-b5e3-3615d7a9d04e)

**Comment by stonith404** [comment]
I noticed that not every browser supports changing the color of an SVG based on the color scheme. 

I've added an option to set a logo for each color scheme now. This should fix the issue.
