### ISSUE TITLE
Integration with Gravatar

### ISSUE THREAD

**Issue by edbourque0** [stonith404/pocket-id#34]
### Feature description

Use gravatar for the profile pictures.

### Pitch

Make use of [Gravatar](https://docs.gravatar.com) to retreive the profile picture of users. This integration make the management of profile pictures very easy without much code. Maybe add a toggle for each user if they want to use grafana as a profile picture (or no toggle and applies to everyone). 
Also, would be cool to have the profile picture shown when the user is logged in and grants access to an app.

**Comment by stonith404** [comment]
Added in`v0.6.0`.
