### ISSUE TITLE
Show external IP address in the audit when using Docker

### ISSUE THREAD

**Issue by edbourque0** [stonith404/pocket-id#35]
### Feature description

Show external IP address in the audit page when using docker.

### Pitch

Since docker uses the container’s network to communicate, I think it has issues getting the real client’s IP address so it logs it’s internal docker IP at every connection. This IP is also the one sent in suspicious activity email (and the condition that triggers it). So I think this would be something to look into. Also, could be cool to have the location (country ou city) of the IP.

![IMG_6991](https://github.com/user-attachments/assets/abd9b5ca-bbfb-40a4-a9d1-378922670068)

**Comment by stonith404** [comment]
Do you have a reverse proxy in front? If so, did you set the `TRUST_PROXY` environment variable to true?

**Comment by edbourque0** [comment]
That was it, sorry about that.
Thanks!
