### ISSUE TITLE
🐛 Bug Report: Gravatar logo used as profile picture when user has no Gravatar account

### ISSUE THREAD

**Issue by edbourque0** [stonith404/pocket-id#36]
### Reproduction steps

1. Create user with an email not associated with a Gravatar account
2. Login as the user
3. Refresh the page to load the profile picture (if needed)

### Expected behavior

The profile picture should be the user's initials just like it was before the Gravatar integration (#34) .

### Actual Behavior

The profile picture shows the Gravatar logo.
I assume that this is because the url of the gravatar picture is not associated to any user so i returns the Gravatar logo.

Maybe add some logic to check if the user exists on gravatar and if not, show the initials.

![image](https://github.com/user-attachments/assets/90c05462-bb10-45d4-ab79-9eddebab7f81)

**Comment by stonith404** [comment]
Thanks for reporting this. In `v0.7.1` it should take the initials if the Gravatar avatar doesn't exist.
