### ISSUE TITLE
🐛 Bug Report: Integration with EspoCRM fails due to missing KID in the jwks.json

### ISSUE THREAD

**Issue by redispade** [stonith404/pocket-id#37]
### Reproduction steps

I added pocket-id as OIDC provider in EspoCRM. It authenticates the user but when returning to Espo then fails with a 500 error.
You can replicate this with your own selfhosted espocrm instance or reach out to me for testing.

### Expected behavior

.well-known/jwks.json should have the KID value(but I don't know how exactly that works)

### Actual Behavior

 I enabled debugging in Espo and I get this:
`[2024-10-08 11:11:05] CRITICAL: (0) Bad JWK value. :: GET /App/user :: /var/www/html/application/Espo/Core/Authentication/Jwt/Keys/Rsa.php(56)`

which goes down to this line of code that checks if any of the values (KID or KTY) are missing
https://github.com/espocrm/espocrm/blob/96134378955a47ef1359ec38e3c755eeeff9bc5f/application/Espo/Core/Authentication/Jwt/Keys/Rsa.php#L56

I checked the json on my instance and indeed it's missing KID value(KTY is present as RSA)

**Comment by stonith404** [comment]
Thanks for reporting. This should be fixed in `v0.8.1`.
