### ISSUE TITLE
🚀 Feature: Unraid Template

### ISSUE THREAD

**Issue by nwithan8** [stonith404/pocket-id#4]
### Feature description

A template for Unraid users to easily install and run the Docker container on their system via the common Community Apps plugin.

### Pitch

Saw your Reddit post about this project earlier today and wanted to make an Unraid template so that Unraid users can easily start using and testing out your app.

I've already made the template here: https://github.com/nwithan8/unraid_templates/blob/main/templates/pocket_id.xml

It should be live on the Unraid Community Apps store in a few hours: https://unraid.net/community/apps?q=pocketid#r

**Comment by stonith404** [comment]
Great, thank you. Should I add anything to the README, or do Unraid users usually not visit the README?

**Comment by nwithan8** [comment]
> Great, thank you. Should I add anything to the README, or do Unraid users usually not visit the README?

If you want to advertise that it's available, sure.

I imagine most users are going to find the app via the store and simply install it rather than visiting this GitHub repo, so they might not end up reading the README.

**Comment by stonith404** [comment]
Ok. Do you think it's enough if I just put the link to the template in the docs?

**Comment by nwithan8** [comment]
You can just say it's available in the Community Apps store by searching "Pocket ID". Unraid users will know how to find it.

**Comment by stonith404** [comment]
Great, I've added it :)

**Comment by HurracaineIke** [comment]
I tried doing a pull of this today and it looks like the repository is not available?

`Unable to find image 'stonith404/pocket-id:latest' locally
docker: Error response from daemon: pull access denied for stonith404/pocket-id, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

The command failed.`

**Comment by nwithan8** [comment]
Well, the problem seems to be that the Pocket-ID image is no longer published on Docker Hub. @stonith404 might be able to weigh in?

**Comment by kmendell** [comment]
@nwithan8 Correct, We moved it to GitHub, the new image is `ghcr.io/pocket-id/pocket-id`

**Comment by nwithan8** [comment]
> @nwithan8 Correct, We moved it to GitHub, the new image is `ghcr.io/pocket-id/pocket-id`

Sounds good, I'll update the template accordingly

**Comment by nwithan8** [comment]
> [@nwithan8](https://github.com/nwithan8) Can you update the unraid template with the latest changes with v1.0 [pocket-id.org/docs/setup/migrate-to-v1](https://pocket-id.org/docs/setup/migrate-to-v1/)

Done in https://github.com/nwithan8/unraid_templates/commit/aa7d24d99999a6ec2ba159213fee47e69aecffcc

**Comment by TheACwarriors** [comment]
The Template for Unraid is outdated. Since Version 2.0 It requires the ENCRYPTION_KEY Variable. Could we update the template on unraid?

**Comment by nwithan8** [comment]
> The Template for Unraid is outdated. Since Version 2.0 It requires the ENCRYPTION_KEY Variable. Could we update the template on unraid?

Thanks. Fixed in https://github.com/nwithan8/unraid_templates/commit/a1380c927d1ceaecabc6c08cd0f047b6483ea4cd
