### ISSUE TITLE
🐛 Bug Report: Memos Identifier invalid 

### ISSUE THREAD

**Issue by Node815** [stonith404/pocket-id#45]
### Reproduction steps

When I add the necessary information for memos from usememos.com it successfully directs to the server and completes the login, but upon returning to the memos server, it errors out with a message saying the value is not found in the claims field or is empty.

In the case of above,  it really doesn't matter what I put in there, I've tried name, profille, preferred_username and it returns the same value.  
These are my settings and the required identifier from the app:

![image](https://github.com/user-attachments/assets/cc8dfc47-3a0e-42b0-a013-d46ed7d043bf)

As this is the required field, I'm not really sure what the correct identifier for this would be.  
This page gives some breakdown of the configuration for three services, but not this app yet. :) 
https://www.usememos.com/docs/advanced-settings/sso

In every instance, it says to use the preferred_username which in this case doesn't work.

### Expected behavior

It should pass the login auth to the memos app. 

### Actual Behavior

It actually returns to the app with this error.  In this case, I used openid as the identifier. 
![image](https://github.com/user-attachments/assets/93fbddc0-2b05-4b7c-8f37-60bf29d48474)

**Comment by stonith404** [comment]
I think you've entered the wrong "user endpoint" URL. It should be `https://<pocket-id>/api/oidc/userinfo`.

Here is my configuration that is working:
![image](https://github.com/user-attachments/assets/4ea80027-3b34-4560-9d85-aaf101c99547)

**Comment by Node815** [comment]
Yup!  That worked!  Not sure how I missed it.  Thank you!
