### ISSUE TITLE
🐛 Bug Report: Komga needs "email_verified", and I can't seem to find that option in Pocket ID

### ISSUE THREAD

**Issue by lucky0wl-sketch** [stonith404/pocket-id#47]
### Reproduction steps

When I configure Komga to use Open ID, and sign in with my Pocket ID account, it goes through and redirects properly, however it then fails and gives me an error pop up with the following message:  "OpenID Connect login error: no email_verified attribute".

(This is my first time using Open ID, and my first time using GitHub's report feature, thank you in advance for your patience. I have been loving Pocket ID, thanks for making it!)

### Expected behavior

It should complete the sign in and take me to the dashboard where my comics are.

### Actual Behavior

It throws up the  "OpenID Connect login error: no email_verified attribute" message and does not send me in to my dashboard.

**Comment by stonith404** [comment]
This claim has been added in `v0.11.0`.

**Comment by lucky0wl-sketch** [comment]
Thank you for fixing this! Is there anything I need to do to update my users to have this change reflected?

**Comment by stonith404** [comment]
No, but you can change it in the settings if the value should be true or false. If you're sure that every user owns its email address, you can set it to true.

![Screenshot 2024-10-25 at 21 54 25@2x](https://github.com/user-attachments/assets/ba9177ea-b872-468a-a133-8d0d791ce826)
