### ISSUE TITLE
🐛 Bug Report: (More of a feedback)  - Powered by text in light mode is broken

### ISSUE THREAD

**Issue by Node815** [stonith404/pocket-id#48]
### Reproduction steps

If you use your computer in light mode instead of dark mode, the Powered by Pocket-ID doesn't show.  
![image](https://github.com/user-attachments/assets/b13a9017-e340-48bd-ba96-df1f2311cb62)

However, when you are in dark mode, it does:
![image](https://github.com/user-attachments/assets/8c4e15ca-6e44-464f-8506-80f71374ea88)

### Expected behavior

It should adapt to a darker color to show the product name instead of a gap or seemingly transparent. (Other than white on white like it is now)

### Actual Behavior

The verbiage _Pocket-ID_ is transparent because the text is white and the background is white.

**Comment by stonith404** [comment]
Thanks for reporting. This has been fixed in `v0.11.0`.
