### ISSUE TITLE
🐛 Bug Report: Unable to Add Passkey

### ISSUE THREAD

**Issue by dhop90** [stonith404/pocket-id#5]
### Reproduction steps

1) From a fresh install, access initial configuration @ http://pocketid/admin/setup
2) Modify admin account with firstname, lastname, email and username
3) attempt to "Add Passkey"
4) 1Password dialog window pops up to either Save passkey to New Item or Update Existing
4a) In ether case I get 1Password encountered a problem - Try Again and "An unknown error occurred" error message is briefly displace at bottom of page

### Expected behavior

It should allow me to add a passkey

### Actual Behavior

Nothing happens, an error is displayed.
following log message is outputted "[GIN] 2024/08/12 - 22:43:30 | 200 |   57.093234ms |    10.244.7.254 | GET      "/api/webauthn/register/start"

**Comment by dhop90** [comment]
Adding additional configuration information:
Running in kubernetes environment, PUBLIC_APP_URL = http://pocket-id.pocketid.svc.cluster.local which is a kubernetes internal service, I connect to the app at url https://pocketid.domain.org, SSL is provided via duckdns and kubernetes ingress.  I'm running the latest docker image stonith404/pocket-id:v0.1.1

**Comment by stonith404** [comment]
Can you try to set the `PUBLIC_APP_URL` to https://pocketid.domain.org? Webauthn requires an `RPId` which is derived from the `PUBLIC_APP_URL` and when the `RpId` isn't the same as the domain where you try to add a passkey, it won't work.

**Comment by stonith404** [comment]
That's a strange error because it seems like the value of `BackupEligible` is not the same while logging in as when adding the passkey.  Do you sometimes have issues with passkeys of 1Password on other services?

**Comment by dhop90** [comment]
Not a big user of passkeys yet.  What limited use I do have is through my job and I do not have any issues.  When I added the passkeys for both accounts, I did not use 1Password.  I've tried delete all passkeys as well as blowing away the config and pocket-id.db and starting fresh.  If it makes a difference, I'm using chrome on a macbook pro, M1 model running Sonoma 14.6.1

**Comment by stonith404** [comment]
Okay thanks. Which passkey do you use?

**Comment by dhop90** [comment]
I'm using icloud keychain

**Comment by dhop90** [comment]
getting same error message when I add a different passkey via camera phone and save to 1Password

**Comment by stonith404** [comment]
Thanks, I think I have found the issue. Can you try `v0.1.3`? The Docker image should be available in around 20 minutes.

**Comment by dhop90** [comment]
I was able to login, now to configure a client.  Thanks for the quick turn-around
