### ISSUE TITLE
🐛 Bug Report: DEV Image cannot create non admin users

### ISSUE THREAD

**Issue by donkevlar** [stonith404/pocket-id#50]
### Reproduction steps

Using the dev docker image. Create a new user in the UI with all details. Leaving "Admin" box as false. 

### Expected behavior

Create the non-admin new user without errors.

### Actual Behavior

Prompts with a 'isAdmin' is required. Note that if you do check 'Admin' this prompt goes away and the user is created successfully. However, you cannot remove the admin role from a user once it has been added also. 

Log spits out: 

`Error #01: Key: 'UserCreateDto.IsAdmin' Error:Field validation for 'IsAdmin' failed on the 'required' tag`

**Comment by stonith404** [comment]
Thanks for reporting. This should be fixed.
