### ISSUE TITLE
🚀 Feature: Automatic Encyrpted Backup

### ISSUE THREAD

**Issue by donkevlar** [stonith404/pocket-id#55]
### Feature description

A way for an admin to setup automatic backups on a given schedule. Also, with this a simple way to migrate from a backup could be part of the same menu item. 

### Pitch

Since the app is still fairly new, I am running into small issues saving (I'll open a separate issue report for this). However, it would be nice to have an automatic backup solution for this in case it does happen.

Primary reasons (for me):
1) Migrating to new or old versions without breaking things by accident. ( I did this the other day while testing the dev image. I was a bit hasty and didn't look into your comment wooops). 

2) I prefer to have some form of backup built in. If there is a manual method, it needs to be defined.

**Comment by stonith404** [comment]
All data is inside the 'data' folder. You can create a really simple bash script that zips the folder and encrypts it, and then you can automate it with a cron job. 
Because this is a really easy process, I don't see the need for this feature. Thanks anyways for the suggestion.
