### ISSUE TITLE
PocketID in combination with Caddy Secure / authcrunch

### ISSUE THREAD

**Issue by PaddyPat** [stonith404/pocket-id#57]
### Feature description

Dear stonith404,

could you give me a hint how to solve this issue with caddy and caddy secure plugin?

I'm using caddy secure as auth portal. 
Pocketid supports groups, which is really great in combination with caddy secure (add user to group xy - menu entry is visible and domain is accessible) .
 
But I need to run it on  two different server, one for pocketit on port 443, one for authcrunch (caddy secure) on 443.

Why two servers?

In authcrunch Caddyfile (https://github.com/authcrunch/authcrunch.github.io/blob/main/assets/conf/oauth/generic/Caddyfile) for oidc, 
the domain (Keycloak) is listed in line 16/17. This means, ts listed before its declared at the bottom of the caddy file to offer it (line 70 for pocketid as an example)

If I bind it to pocketid:80, it also fails and I have no more idea, howto run both apps on 443 on one machine.

Do you have any hint for me to solve this issue without using two servers?
Thanks for your work and your help. 👍

### Pitch

.

**Comment by PaddyPat** [comment]
For others how I solved it:
Run pocketid only behind cloudflare tunnel. 
This allowed me during execution from authcrunch to validate oidc connection.

many other hints are welcome

**Comment by stonith404** [comment]
I don’t use Authcrunch, so I can’t provide detailed assistance with it. However, I think a Cloudflare tunnel is a solid solution. Alternatively, you could try running Pocket ID behind Authcrunch and disabling authentication for Pocket ID within Authcrunch, I'm not sure if this is possible though. Another option could be placing Caddy as a reverse proxy in front of both Authcrunch and Pocket ID.
