### ISSUE TITLE
🐛 Bug Report: Browser unsupported for Arc browser with bitwarden extension installed

### ISSUE THREAD

**Issue by TheZoker** [stonith404/pocket-id#6]
### Reproduction steps

Use arc browser (https://arc.net/)

### Expected behavior

Work

### Actual Behavior

I use the arc browser on macOS and my installed bitwarden extension handles the passkeys.
When I visit the setup page of pocket id, I get this error:

![image](https://github.com/user-attachments/assets/db45e4db-a555-47bf-8034-4b6d7ad89d2b)

When I test this on https://webauthn.io/ everything works as expected.

**Comment by stonith404** [comment]
That's strange because I'm using Arc and Bitwarden too and it works for me. Can you run the following code in the browser JS console and share the output?
```js
window?.PublicKeyCredential !== undefined && typeof window.PublicKeyCredential === 'function'
```

And if you open the page in a private browser window where Bitwarden isn't installed, do you still get the error?

**Comment by TheZoker** [comment]
This is the output:

<img width="1505" alt="Bildschirmfoto 2024-08-14 um 14 18 35" src="https://github.com/user-attachments/assets/6881826a-cc2b-485e-bf9b-6a3915a08c05">


Same for the incognito window without bitwarden active ...

**Comment by stonith404** [comment]
Okay thanks. Are you using the latest version of Arc and which MacOS version are you using? Do you have any plugins enabled in the private browser window?

Additionally can you share the output of `window.PublicKeyCredential` when you paste this into the console?

**Comment by TheZoker** [comment]
I'm using:

- Arc: Version 1.55.0 (52417)
- macOS: 15.0 Beta (24A5320a)
- No extensions enabled in private browsing

Output of window.PublicKeyCredential:

<img width="1504" alt="Bildschirmfoto 2024-08-14 um 16 14 40" src="https://github.com/user-attachments/assets/0a1be836-4e44-4336-a01a-978ec6fae7a5">

**Comment by stonith404** [comment]
Do you run Pocket ID on localhost? If not, do you use https?

**Comment by dhop90** [comment]
I saw the this issue when I didn't run using ssl certs.  I think it nees to be protected using https://

**Comment by Bartrpc** [comment]
@TheZoker In order for PocketID to work, you need to expose PocketID using a reverse proxy like Nginx, Cloudflared, or something similar with your subdomain.

**Comment by TheZoker** [comment]
Ah make sense. I wanted to first try this on localhost to test it out. But I will use my reverse proxy for that. Thanks!

**Comment by Bartrpc** [comment]
I've properly configured pocket and add it to Cloudflare as OIDC provider. It's working as it should be with Opera, Chrome and Edge, however @TheZoker @stonith404, it's not working with Arc. I supose it's a lack of some feature inside Arc. However,I wanted to let You know that, so bear in mind that fact.

**Comment by stonith404** [comment]
@Bartrpc Hm okay strange. I'm using Arc on MacOS and it's working for me. Do you get the browser unsupported error?

**Comment by Bartrpc** [comment]
I tersting fact is that there is no "unsupported browser" error. Pocket can't connect with Bitwarden extension. I'm using arc on Windows btw🙂

**Comment by Bartrpc** [comment]
@stonith404 lol, idk what is happening, but on my main laptop on Win11 with Arc, it's working 😅

**Comment by stonith404** [comment]
@Bartrpc Yeah that's strange. https://github.com/bitwarden/clients/issues/8876 may be related but I'm not sure as I don't use Arc on Windows.
