### ISSUE TITLE
🐛 Bug Report: All dates are set to 1/1/1, 12:17:30 AM

### ISSUE THREAD

**Issue by stephanvane** [stonith404/pocket-id#60]
### Reproduction steps

Run pocket-id locally or in a Kubernetes cluster. 

### Expected behavior

It should store/display the correct date and time

### Actual Behavior

it shows all dates and times as 1/1/1, 12:17:30 AM. For example the "added on" date for keys, and the dates in the Audit log.

<img width="829" alt="Screenshot 2024-11-05 at 16 43 37" src="https://github.com/user-attachments/assets/b4d15119-effb-4782-954f-12d77576654a">

**Comment by Node815** [comment]
I run mine in Docker and have a similar issue:
![image](https://github.com/user-attachments/assets/f216a724-6ddc-414b-9136-b6466b34ad16)
Both my shell and container dates for the server at least concur the correct date:
![image](https://github.com/user-attachments/assets/28b384ee-976e-4929-a771-407ffe15f072)

Following the container log for my log out and back in shows:

![image](https://github.com/user-attachments/assets/1dfac8d6-841b-4710-9624-d496edd0dfdd)

**Comment by jbalatero** [comment]
I can confirm similar issue.

**Comment by willowless** [comment]
Confirm +1, Docker x86_64

**Comment by stonith404** [comment]
Thanks, I'll look into it as soon as I'm back from vacation.

**Comment by stonith404** [comment]
This is fixed in `v0.14.0`. Thanks for reporting.
