### ISSUE TITLE
🚀 Feature: Add more options for mail server

### ISSUE THREAD

**Issue by phil3741** [stonith404/pocket-id#61]
### Feature description

Currently we can define an SMTP server for Mail notifications, which works fine for external Mail servers, but does not allow to disable cert checks for local smtp servers (like protonmail bridge).

Disabling Cert Checks, as well as a "Test E-Mail" Button would improve the configuration.

### Pitch

I want to use the local protonmail bridge on my server to send e-mails to the users.

While protonmail only listens on 127.0.0.1, we can forward the listening via rinetd to docker.

Despite reaching the smtp server, the sending still fails with the following error:

2024/11/08 08:16:49 Failed to send email to '<EMAIL-ADDRESS': failed to send email: tls: failed to verify certificate: x509: certificate is valid for 127.0.0.1, not <IP-ADDRESS>

Sending SMTP mails from other clients with disabled certcheck works, but this option is not available in the Pocket ID UI

**Comment by phil3741** [comment]
works like a charm in 0.15.0!

Many many thanks!

**Comment by stonith404** [comment]
Great :)
