### ISSUE TITLE
🚀 Feature: healthcheck endpoint

### ISSUE THREAD

**Issue by jfroy** [stonith404/pocket-id#70]
### Feature description

It would be nice to have a healthcheck endpoint to use with k8s probes. There are many Gin middelwares/packages for that.

### Pitch

Kubernetes and other service control planes can monitor services for liveness and readiness, restart the service when detecting a failure, and direct traffic to ready instances (e.g. do rolling updates w/o disruption).

**Comment by stonith404** [comment]
Added in `v0.16.0`. The endpoint is available at the `/health` route. If you use Docker Compose, please update your `docker-compose.yml` with the newest one.
