### ISSUE TITLE
🐛 Bug Report: Disappearing Logo for app

### ISSUE THREAD

**Issue by durandguru** [stonith404/pocket-id#82]
### Reproduction steps

I have set an logo for an OIDC client. When i change the name later or callback url, I save the settings and reopen the app and the logo is gone.

### Expected behavior

logo stays put

### Actual Behavior

![image](https://github.com/user-attachments/assets/27403f58-608a-4581-abda-d8b46d77922f)

![image](https://github.com/user-attachments/assets/5d78b29a-cedc-4251-b1c1-d891e21e7023)

**Comment by stonith404** [comment]
Thanks for reporting this. This should be fixed in `v0.21.0`.
